# -*- coding: utf-8 -*-
"""Object detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ePv7UzbU5x1Thy-cY0moA7YQyqrxERMm
"""

!pip install opencv-contrib-python==3.4.13.47 --force-reinstall

pip install cvlib

import cv2
import matplotlib.pyplot as plt
import numpy as np
import cvlib as cv
from cvlib.object_detection import draw_bbox

im = cv2.imread("human.jpg")

plt.imshow(im[:,:,::-1])

bbox , conf =cv.detect_face(im)

bbox

conf

labels = []
for i in range(len(conf)):
  labels.append('person')

im2 = draw_bbox(im,bbox,labels,conf)
plt.imshow(im2)

plt.imshow(im2[:,:,::-1])

"""## Object detection with YOLO"""

im = cv2.imread("yolo.jpeg")

bbox ,labels, conf =cv.detect_common_objects(im)

im2 = draw_bbox(im,bbox,labels,conf)
plt.imshow(im[:,:,::-1])

labels

